### ISSUE TITLE
Please tag and version this project

### ISSUE THREAD

**Issue by jredville** [itsjamie/gin-cors#8]
Tags and versions aid in packaging for things like .deb files, and for anyone wanting to use Glide and other version based package managers to version their dependencies. It would also help ensure that if you make a breaking change, we don't pull it down until we are ready.

**Comment by itsjamie** [comment]
@jredville I've pushed a 1.0.0 tag at the current master. Is that good?

**Comment by jredville** [comment]
Perfect! Thank you. If I could talk you into using semver to tag future releases that would be helpful as well. That way I can lock to ~1.0.0 and get bug fixes.

**Comment by itsjamie** [comment]
Sure. 

Since it's so headers based, and I don't imagine the public interface changing unless gin itself does. 

I'll consider adding any headers that affects performance with CDNs a major bump. Like when I added `Vary: Origin`.

Minors would be additional configuration to the struct that don't impact current users unless they opt-in.
